"use client";

import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { formatDateTime } from "@/lib/format";
import type { Insight } from "@/lib/types";
import { RiskBadge, StatusBadge } from "./ui";

type State =
  | { phase: "idle" }
  | { phase: "loading"; refresh: boolean }
  | { phase: "error"; message: string; code: string };

const SENTIMENT = {
  positive: { icon: "✓", className: "bg-good-wash text-good-ink" },
  negative: { icon: "!", className: "bg-critical-wash text-critical-ink" },
  neutral: { icon: "•", className: "bg-surface-2 text-ink-2" },
};

export function InsightPanel({ supplierId, initialInsight }: { supplierId: number; initialInsight: Insight | null }) {
  const [insight, setInsight] = useState<Insight | null>(initialInsight);
  const [cached, setCached] = useState(false);
  const [state, setState] = useState<State>({ phase: "idle" });
  const loading = state.phase === "loading";

  async function generate(forceRefresh: boolean) {
    setState({ phase: "loading", refresh: forceRefresh });
    try {
      const res = await api.generateInsight(supplierId, forceRefresh);
      setInsight(res.data);
      setCached(res.meta.cached);
      setState({ phase: "idle" });
    } catch (err) {
      const e = err instanceof ApiError ? err : new ApiError(0, "UNKNOWN", "Something went wrong.");
      setState({ phase: "error", message: e.message, code: e.code });
    }
  }

  return (
    <section className="rounded-xl border border-line bg-surface p-5" aria-live="polite" aria-busy={loading}>
      <header className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span aria-hidden className="grid size-7 place-items-center rounded-lg bg-accent text-sm text-accent-ink">
            ✦
          </span>
          <div>
            <h2 className="text-sm font-semibold text-ink">AI Sustainability Insight</h2>
            <p className="text-xs text-muted">Generated by an LLM from this supplier&apos;s metrics</p>
          </div>
        </div>
        <button
          type="button"
          onClick={() => generate(Boolean(insight))}
          disabled={loading}
          className="rounded-lg bg-accent px-3.5 py-1.5 text-sm font-medium text-accent-ink transition hover:opacity-90 disabled:cursor-wait disabled:opacity-60"
        >
          {loading ? "Analysing…" : insight ? "Regenerate" : "Generate insight"}
        </button>
      </header>

      {state.phase === "error" && (
        <div role="alert" className="mb-4 rounded-lg border border-critical/30 bg-critical-wash px-3 py-2 text-sm text-critical-ink">
          <strong className="font-semibold">Couldn&apos;t generate insight.</strong> {state.message}
          <span className="ml-1 text-xs opacity-70">({state.code})</span>
        </div>
      )}

      {loading ? (
        <div className="space-y-3" aria-label="Generating insight">
          <p className="text-sm text-ink-2">Preparing supplier context and asking the model…</p>
          {[92, 80, 64].map((w) => (
            <div key={w} className="h-3 animate-pulse rounded bg-surface-2" style={{ width: `${w}%` }} />
          ))}
        </div>
      ) : insight ? (
        <InsightBody insight={insight} cached={cached} />
      ) : (
        <p className="rounded-lg bg-surface-2 px-4 py-6 text-center text-sm text-ink-2">
          No insight yet. Generate one to get an AI summary of this supplier&apos;s performance, key findings and recommended actions.
        </p>
      )}
    </section>
  );
}

function InsightBody({ insight, cached }: { insight: Insight; cached: boolean }) {
  return (
    <div>
      <div className="mb-3 flex flex-wrap gap-2">
        <RiskBadge level={insight.riskLevel} />
        <StatusBadge status={insight.requiresReview ? "review" : "ok"} />
      </div>

      <p className="text-[15px] leading-relaxed text-ink">{insight.summary}</p>

      <div className="mt-5 grid gap-5 md:grid-cols-2">
        <div>
          <h3 className="mb-2 text-xs font-semibold tracking-wide text-muted uppercase">Key findings</h3>
          <ul className="space-y-2">
            {insight.keyFindings.map((f, i) => {
              const s = SENTIMENT[f.sentiment];
              return (
                <li key={i} className="flex gap-2 text-sm">
                  <span aria-hidden className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-full text-[11px] font-bold ${s.className}`}>
                    {s.icon}
                  </span>
                  <span>
                    <span className="font-medium text-ink">{f.metric}: </span>
                    <span className="text-ink-2">{f.observation}</span>
                  </span>
                </li>
              );
            })}
          </ul>
        </div>
        <div>
          <h3 className="mb-2 text-xs font-semibold tracking-wide text-muted uppercase">Recommended actions</h3>
          <ol className="list-decimal space-y-2 pl-5 text-sm text-ink-2 marker:text-muted">
            {insight.recommendations.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ol>
        </div>
      </div>

      <footer className="mt-5 flex flex-wrap gap-x-4 gap-y-1 border-t border-line pt-3 text-xs text-muted">
        <span>
          {insight.provider === "mock" ? "Mock mode (no API key)" : "Gemini"} · {insight.model}
        </span>
        <span>{formatDateTime(insight.createdAt)}</span>
        <span>{cached ? "Served from cache (data unchanged)" : `${(insight.latencyMs / 1000).toFixed(1)}s`}</span>
      </footer>
    </div>
  );
}
